version: "3"

services:
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    restart: always
    volumes:
      - "./data/database:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"

