name: Build and deploy api
on: push

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          dockerfile: ./Dockerfile-fastapi
          registry: eu.gcr.io
          project_id: ${{ secrets.PROJECT_ID }}
          image_name: fastapi