name: Build and deploy api
on: push

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          dockerfile: ./Dockerfile-fastapi
          registry: eu.gcr.io
          project_id: ${{ secrets.PROJECT_ID }}
          image_name: fastapi
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
      - name: Delete old VM
        run: gcloud compute instances delete api --zone "europe-west1-b" --quiet || echo "No machine"
      - name: Create new VM
        env:
          PROJECT_ID: "${{ secrets.PROJECT_ID }}"
        run: gcloud compute instances create-with-container api --container-image eu.gcr.io/${PROJECT_ID}/fastapi --zone "europe-west1-b" --container-privileged --container-restart-policy "always"
