name: Build and deploy backend
on:
  push:
    branches:
      - main

jobs:
  check-for-changes:
    name: Check for changes in backend
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'src/backend/**'

  build-and-push-to-gcr:
    name: Redeploy backend
    needs: check-for-changes
    if: ${{ needs.check-for-changes.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/push-to-gcr-github-action@v3.0.2
        with:
          gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          dockerfile: ./Dockerfile-backend
          registry: eu.gcr.io
          project_id: ${{ secrets.PROJECT_ID }}
          image_name: backend
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
          export_default_credentials: true
      - name: Delete old VM
        run: gcloud compute instances delete backend --zone "europe-west1-b" --quiet || echo "No machine"
      - name: Create new VM
        env:
          PROJECT_ID: "${{ secrets.PROJECT_ID }}"
          CONSUMER_KEY: "${{ secrets.CONSUMER_KEY }}"
          CONSUMER_SECRET: "${{ secrets.CONSUMER_SECRET }}"
          ACCESS_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
          ACCESS_TOKEN_SECRET: "${{ secrets.ACCESS_TOKEN_SECRET }}"
        run: gcloud compute instances create-with-container backend --container-image eu.gcr.io/${PROJECT_ID}/backend --zone "europe-west1-b" --container-privileged --container-restart-policy "always" --container-env CONSUMER_KEY=$CONSUMER_KEY,CONSUMER_SECRET=$CONSUMER_SECRET,ACCESS_TOKEN=$ACCESS_TOKEN,ACCESS_TOKEN_SECRET=$ACCESS_TOKEN_SECRET
